var databaseConfig = {
    liveSyncDatabases: ["patients_records", "visits", "stages", "mnh_stats"],
    periodicSyncDatabases: [
        "programs",
        "facilities",
        "drugs",
        "regimens",
        "custom_regimen_ingredients",
        "regimen_extras",
        "relationship",
        "traditional_authorities",
        "villages",
        "concept_sets",
        "concept_names",
        "districts",
        "diagnoses",
        "wards",
        "departments",
        "locations",
        "stock",
        "dde",
        "lab_accession_numbers",
        "test_types",
        "specimens",
        "test_result_indicators",
        "printer_configurations",
        "regimen_starter_packs",
        "roles",
        "arv_drugs",
        "global_properties",
        "regimen_extras",
        "user_properties",
        "beds",
        "sections",
        "impow_drugs",
    ],
    editablePeriodicSyncDatabases: ["printer_configurations", "global_properties"],
    locationFilters: {
        patients_records: true,
        visits: true,
        stages: true,
        mnh_stats: true,
        dde: true,
        lab_accession_numbers: true,
        stock: true,
        printer_configurations: true,
        beds: true,
        global_properties: true,
    },
};
